version: "3.8"

services:
  api_gateway:
    image: virtual-classroom/api_gateway:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - vc-network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"

  assignment_service:
    image: virtual-classroom/assignment_service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3004:3004"
    networks:
      - vc-network

  user_service:
    image: virtual-classroom/user_service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3005:3005"
    networks:
      - vc-network
